name: ecommerce
description: A basic e-commerce Flutter app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  get: ^4.6.6
  email_validator: ^3.0.0
  pin_code_fields: ^8.0.1
  http: ^1.2.2
  logger: ^2.5.0
  shared_preferences: ^2.3.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/